### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G5#11]
Which of the following are we going to consider?
Utilize at least two of the following functional programming concepts:
Lambda functions
Map
Reduce
Filter
Generators
List comprehensions

**Comment by tirthbha** [comment]
@reshnashrestha Depends on your code, I think. As in our case, we have used map, generators and lambda function.

**Comment by reshnashrestha** [comment]
yeah, I think we will be using so.
