### ISSUE TITLE
Filter use

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G5#16]
Can you guys explain that how to implement filter to the  classical function " find out the work done by a body moving with different velocities from point A to E (say)?

**Comment by reshnashrestha** [comment]
We need following steps for that:
Define the Problem:
Discretize the Path
Calculate Force at Each Point
Calculate Work at Each Step
Sum the Work
Numerical Integration
Implement a Filter
Final Result

**Comment by tirthbha** [comment]
@reshnashrestha but have not used force term in our problem.

**Comment by reshnashrestha** [comment]
you can skip that part and in that manner, you can add your process.
