### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G5#23]
I think there is only one member in this group, as saw only one fork in the  group.

**Comment by reshnashrestha** [comment]
This is the 2 member group. I think @AhmedCode99 has not forked yet.

**Comment by tirthbha** [comment]
Probably, he forgot to sent a request to the professor.

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework3G5/assets/143649458/f710d09b-05dd-48a8-a9a1-8e7bd2762997)
Well Thank you for noticing, but he is already a member.
