### ISSUE TITLE
Your Project

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G5#25]
Hi G5 team,

I am curious about your project. May I know which classical mechanics problem you guys are working on?

**Comment by reshnashrestha** [comment]
@s4il3sh We are going to work on projectile motion with air resistance. What about you?

**Comment by s4il3sh** [comment]
We are working on finding the spring constant and the energy stored in it.

**Comment by reshnashrestha** [comment]
Sounds, good.
