### ISSUE TITLE
About the folder

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G5#26]
As you mentioned in issue [#](https://github.com/ubsuny/23-Homework2G5/issues/56#issue-1925164843) making folders. 

It's easy!
- click add files at your repository
- type your folder_name and add /
- after slash type in your file name.
which should look like this (i.e. folder_name/file_name)
Then, you are done!

**Comment by reshnashrestha** [comment]
Oh Okay thank you @s4il3sh I will try this.
