### ISSUE TITLE
Issues with unit tests. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G5#42]
Hello, As, per my knowledge, the unit test is something, to check whether the code is correct or not, The unit test code, is a different code which checks the original code right?. To me more precise, should it be the same code and checking for different inputs, or it should be a different code?
Thank you,

**Comment by reshnashrestha** [comment]
I believe that it utilizes the code for checking the accuracy of the code. It necessarily does not need to be the same code. @uarif
