### ISSUE TITLE
Heavy sphere

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G5#45]
I am confused why you mentioned heavy sphere in the description section. Can you please clarify @AhmedCode99 ?

**Comment by AhmedCode99** [comment]
This is an inline equation: $E=mc^2$.

**Comment by AhmedCode99** [comment]
The equation I used only works for heavy ball projectiles. The drag force is generally given $F_d=-b_1 * v - b_2 * v^2 -b_3 v^3$. Which is a Taylor expansion, and can go up to $n$ coefficients. For heavy balls, only the $b_2$ is dominant. However, for other kinds of projectiles, one will have to consider the other $b$ coefficients. It is also important to note the $b$ are experimentally determined.

**Comment by AhmedCode99** [comment]
This is a result of the stokes model for drag. Really interesting stuff, if you like fluid mechanics.
