### ISSUE TITLE
pycodestyle checked your projectile_module.py file

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G5#52]
Hi guys, I have used pycodestyle to check your code, it is throwing out a lot of comments to improve the quality of the code. Just letting you know if you guys want to follow some of the suggestions.
![image](https://github.com/ubsuny/23-Homework3G5/assets/144289804/04dee096-9983-45af-8fdd-f6ac0457dd72)
![image](https://github.com/ubsuny/23-Homework3G5/assets/144289804/f7d06c1d-e6d1-407d-a4fa-37dd8daf869e)
![image](https://github.com/ubsuny/23-Homework3G5/assets/144289804/b0dd1ac0-34f0-4ab5-a163-1657a7ae9c94)

**Comment by AhmedCode99** [comment]
Based, thanks
