### ISSUE TITLE
Help needed to resolve the issue of Group2

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework3G5#55]
We uploaded a new file that contains some changes. However, we found the following error after merging with the main repository.

![Screenshot from 2023-10-06 09-58-24](https://github.com/ubsuny/23-Homework3G5/assets/66480280/8dfe6a2d-0df3-4288-afbb-3e30907f05ba)

**Comment by AhmedCode99** [comment]
This is a google colab issue. Just go to colab, and save a new notebook in git hub.
