### ISSUE TITLE
Labels and Milestones

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G5#6]
@AhmedCode99 we can add milestones for this hw.
And we can discuss on which label we want to add on this issue

**Comment by reshnashrestha** [comment]
@AhmedCode99 Can you add "Notice" as label?

**Comment by AhmedCode99** [comment]
how?

**Comment by reshnashrestha** [comment]
you are a maintainer, you can customize in the label section.

**Comment by AhmedCode99** [comment]
Done
