### ISSUE TITLE
Are we all set?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework3G5#69]
@reshnashrestha are we all set with this homework, or is there more to do?

**Comment by reshnashrestha** [comment]
I guess we are fine.

**Comment by AhmedCode99** [comment]
Nice

**Comment by Mosaddeq107** [comment]
I think you should have created more labels.

**Comment by Mosaddeq107** [comment]
You can check the requirements from the documentation file of your main repository.
