### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G5#7]
@AhmedCode99 Hi as you are the maintainer of this homework, I believe you have access to writing on the "About" section of this repository. 
In my point of view, it will be good to describe in brief on our HW3G5 repository. 
![image](https://github.com/ubsuny/23-Homework3G5/assets/143649458/46f57511-53f8-4cbe-90ef-46e3429813a6)

**Comment by AhmedCode99** [comment]
where can i find that?

**Comment by reshnashrestha** [comment]
on the main page of repo.

**Comment by AhmedCode99** [comment]
Done
